${AUTOTEKA_LOG_DIR}/server-watchdog.log
${AUTOTEKA_LOG_DIR}/server-metrics.log
${AUTOTEKA_LOG_DIR}/server-maintenance.log {
    weekly
    rotate 4
    compress
    delaycompress
    missingok
    notifempty
}
