/var/www/backend/apps/ShopOperator/storage/logs/laravel.log
/var/www/backend/apps/ShopAPI/storage/logs/laravel.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
