/var/www/backend/apps/DatabaseOperator/storage/logs/laravel.log
/var/www/backend/apps/API/storage/logs/laravel.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
